//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by winuae.rc
//
#define IDS_KICKSTART                   1
#define IDS_DISPLAY                     3
#define IDS_HARDDISK                    4
#define IDS_FLOPPY                      5
#define IDS_ABOUT                       6
#define IDS_LOADSAVE                    7
#define IDS_PORTS                       9
#define IDS_MISC                        10
#define IDS_MEMORY                      11
#define IDS_CPU                         12
#define IDS_CHIPSET                     13
#define IDS_EXTTEXT                     100
#define IDS_EXTACTUAL                   101
#define IDS_SOUND                       102
#define IDS_CDROM                       103
#define IDS_FRAMERATE                   104
#define IDS_SECOND                      105
#define IDS_THIRD                       106
#define IDD_KICKSTART                   107
#define IDS_FOURTH                      107
#define IDD_DISPLAY                     108
#define IDS_FIFTH                       108
#define IDD_MEMORY                      109
#define IDS_SIXTH                       109
#define IDD_FLOPPY                      110
#define IDS_SEVENTH                     110
#define IDD_CPU                         111
#define IDS_EIGHTH                      111
#define IDD_ABOUT                       112
#define IDS_NINTH                       112
#define IDD_HARDDISK                    113
#define IDS_TENTH                       113
#define IDS_SELECTADF                   114
#define IDS_ADF                         115
#define IDS_CHOOSEBLANK                 116
#define IDS_SELECTHDF                   117
#define IDS_HDF                         118
#define IDS_SELECTUAE                   119
#define IDS_UAE                         120
#define IDS_SELECTROM                   121
#define IDD_SOUND                       122
#define IDS_ROM                         122
#define IDI_APPICON                     123
#define IDS_SELECTKEY                   123
#define IDI_CPU                         124
#define IDS_KEY                         124
#define IDI_ABOUT                       125
#define IDS_SELECTINFO                  125
#define IDS_NONE                        126
#define IDI_CDROM                       127
#define IDS_VOLUME                      127
#define IDI_HARDDISK                    128
#define IDS_PATH                        128
#define IDS_RW                          129
#define IDI_SOUND                       130
#define IDS_SECTORS                     130
#define IDI_MEMORY                      131
#define IDS_SURFACES                    131
#define IDI_DISPLAY                     132
#define IDS_RESERVED                    132
#define IDS_BLOCKSIZE                   133
#define IDI_FLOPPY                      134
#define IDS_NAME                        134
#define IDD_LOADSAVE                    135
#define IDI_LOADSAVE                    135
#define IDS_DESCRIPTION                 135
#define IDS_ONEINSTANCE                 136
#define IDI_PORTS                       137
#define IDS_INSTALLDIRECTX              137
#define IDD_PORTS                       138
#define IDS_REGKEYCREATEFAILED          138
#define IDS_COULDNOTLOADCONFIG          139
#define IDD_CONTRIBUTORS                140
#define IDS_NOHELP                      140
#define IDD_MISC                        141
#define IDS_MUSTSELECTCONFIG            141
#define IDD_HARDFILE                    142
#define IDS_NOAGA                       142
#define IDD_FILESYS                     143
#define IDS_INVALIDCOMPORT              143
#define IDS_WSOCK2NEEDED                144
#define IDS_UNSUPPORTEDPIXELFORMAT      145
#define IDS_WAVEOUTOPENFAILURE          146
#define IDS_MUSTENTERNAME               147
#define IDS_MUSTSELECTCONFIGFORDELETE   148
#define IDS_DELETECONFIGCONFIRMATION    149
#define IDI_MISC                        150
#define IDS_DELETECONFIGTITLE           150
#define IDC_MYHAND                      151
#define IDS_GFXCARDCHECK                151
#define IDD_DIALOG1                     152
#define IDS_GFXCARDTITLE                152
#define IDD_DEBUGGER                    152
#define IDD_SETINFO                     153
#define IDS_MUSTSELECTPATH              153
#define IDI_ICON1                       153
#define IDS_SETTINGSERROR               154
#define IDD_CHIPSET                     154
#define IDS_MUSTSELECTNAME              155
#define IDI_MOVE_UP                     155
#define IDS_MUSTSELECTFILE              156
#define IDI_MOVE_DOWN                   156
#define IDS_FAILEDHARDFILECREATION      157
#define IDS_CREATIONERROR               158
#define IDS_ERRORTITLE                  159
#define IDS_SELECTFILESYSROOT           160
#define IDS_DEFAULTMIDIOUT              161
#define IDS_DEFAULTMIDIIN               162
#define IDS_CONTRIBUTORS1               163
#define IDS_CONTRIBUTORS2               164
#define IDS_INVALIDPRTPORT              165
#define IDS_SELECTUSS                   166
#define IDS_USS                         167
#define IDS_WRONGOSVERSION              168
#define IDC_RESOLUTION                  1021
#define IDC_SERIAL                      1022
#define IDC_ILLEGAL                     1023
#define IDC_MIDILIST                    1023
#define IDC_MIDIOUTLIST                 1023
#define IDC_SHOWGUI                     1024
#define IDC_MIDIINLIST                  1024
#define IDC_AUTOCONFIG                  1025
#define IDC_PRINTERLIST                 1025
#define IDC_CHIPMEM                     1026
#define IDC_CREATELOGFILE               1026
#define IDC_FASTMEM                     1027
#define IDC_SHOWLEDS                    1027
#define IDC_SLOWMEM                     1030
#define IDC_PARALLEL                    1033
#define IDC_JULIAN                      1040
#define IDC_FASTTEXT                    1043
#define IDC_FASTRAM                     1044
#define IDC_CHIPRAM                     1045
#define IDC_SLOWRAM                     1046
#define IDC_Z3TEXT                      1047
#define IDC_Z3FASTRAM                   1048
#define IDC_Z3FASTMEM                   1049
#define IDC_UAEHOME                     1070
#define IDC_PICASSOHOME                 1071
#define IDC_AMIGAHOME                   1072
#define IDC_WINUAEHOME                  1073
#define IDC_AIABHOME                    1074
#define IDC_CLOANTOHOME                 1075
#define IDC_THEROOTS                    1076
#define IDC_RICHEDIT1                   1091
#define IDC_RICHEDIT2                   1092
#define IDC_CONTRIBUTORS                1124
#define IDC_ASPECT                      1170
#define IDC_BLIT32                      1173
#define IDC_BLITIMM                     1174
#define IDC_LORES                       1176
#define IDC_AFULLSCREEN                 1178
#define IDC_FRAMERATE                   1185
#define IDC_RATETEXT                    1186
#define IDC_XSIZE                       1187
#define IDC_YSIZE                       1188
#define IDC_LM_NORMAL                   1189
#define IDC_LM_DOUBLED                  1190
#define IDC_GFXCARDTEXT                 1191
#define IDC_LM_SCANLINES                1191
#define IDC_P96RAM                      1192
#define IDC_PFULLSCREEN                 1192
#define IDC_P96MEM                      1193
#define IDC_CPU0                        1200
#define IDC_CPU1                        1201
#define IDC_CPU2                        1202
#define IDC_CPU3                        1203
#define IDC_CPU4                        1204
#define IDC_CPU5                        1205
#define IDC_CPU6                        1206
#define IDC_SPEED                       1207
#define IDC_CS_HOST                     1209
#define IDC_CS_68000                    1210
#define IDC_CS_ADJUSTABLE               1211
#define IDC_CS_CPU_TEXT                 1212
#define IDC_CS_CHIPSET_TEXT             1213
#define IDC_COMPATIBLE                  1214
#define IDC_TRUST0                      1215
#define IDC_TRUST1                      1216
#define IDC_TRUST2                      1217
#define IDC_CACHE                       1218
#define IDC_SOUNDSETTINGS               1229
#define IDC_8BIT                        1230
#define IDC_16BIT                       1231
#define IDC_11KHZ                       1232
#define IDC_22KHZ                       1233
#define IDC_44KHZ                       1234
#define IDC_48KHZ                       1235
#define IDC_SOUNDSIZE                   1236
#define IDC_FREQUENCY                   1237
#define IDC_SOUND0                      1238
#define IDC_SOUND1                      1239
#define IDC_SOUND2                      1240
#define IDC_SOUND3                      1241
#define IDC_SOUNDSTYLE                  1242
#define IDC_SOUNDSTYLE0                 1243
#define IDC_STEREO                      1244
#define IDC_SOUNDSTYLE1                 1245
#define IDC_SOUNDINTERPOLATION          1248
#define IDC_INTERPOLATION0              1249
#define IDC_INTERPOLATION1              1250
#define IDC_INTERPOLATION2              1251
#define IDC_STEREOMODE                  1251
#define IDC_STEREOMODE0                 1252
#define IDC_STEREOMODE1                 1253
#define IDC_STEREOMODE2                 1254
#define IDC_DF0TEXT                     1270
#define IDC_DF1TEXT                     1271
#define IDC_DF2TEXT                     1272
#define IDC_DF3TEXT                     1273
#define IDC_EJECT0                      1274
#define IDC_EJECT1                      1275
#define IDC_EJECT2                      1276
#define IDC_EJECT3                      1277
#define IDC_DF0                         1278
#define IDC_DF1                         1279
#define IDC_DF2                         1280
#define IDC_DF3                         1281
#define IDC_CREATE                      1282
#define IDC_CREATE_RAW                  1283
#define IDC_SNAPSHOTNAME                1284
#define IDC_SNAPSHOT                    1285
#define IDC_DOSAVESTATE                 1286
#define IDC_DOLOADSTATE                 1287
#define IDC_PORT0_JOY0                  1300
#define IDC_PORT0_JOY1                  1301
#define IDC_PORT0_MOUSE                 1302
#define IDC_PORT0_KBDA                  1303
#define IDC_PORT0_KBDB                  1304
#define IDC_PORT0_KBDC                  1305
#define IDC_PORT1_JOY0                  1306
#define IDC_PORT1_JOY1                  1307
#define IDC_PORT1_MOUSE                 1308
#define IDC_PORT1_KBDA                  1309
#define IDC_PORT1_KBDB                  1310
#define IDC_PORT1_KBDC                  1311
#define IDC_PORT0                       1312
#define IDC_PORT1                       1313
#define IDC_EDIT                        1334
#define IDC_REMOVE                      1335
#define IDC_VOLUMELIST                  1336
#define IDC_UP                          1337
#define IDC_DOWN                        1338
#define IDC_NEW_FS                      1339
#define IDC_NEW_HF                      1340
#define IDC_PATH_NAME                   1362
#define IDC_SELECTOR                    1363
#define IDC_VOLUME_NAME                 1364
#define IDC_SECTORS                     1365
#define IDC_HEADS                       1366
#define IDC_RESERVED                    1367
#define IDC_BLOCKSIZE                   1368
#define IDC_SECTORS_TEXT                1370
#define IDC_SURFACES_TEXT               1371
#define IDC_RESERVED_TEXT               1372
#define IDC_RESERVED_TEXT2              1373
#define IDC_BLOCKSIZE_TEXT              1374
#define ID_OK                           1375
#define IDC_HARDFILE_DIR_TEXT           1377
#define IDC_RW                          1379
#define IDC_ROMFILE                     1390
#define IDC_KEYFILE                     1391
#define IDC_KICKCHOOSER                 1392
#define IDC_KEYCHOOSER                  1393
#define IDC_ROMFILE2                    1394
#define IDC_ROMCHOOSER2                 1395
#define IDC_SAVE                        1400
#define IDC_LOAD                        1401
#define IDC_DELETE                      1403
#define IDC_CONFIGLIST                  1404
#define IDC_EDITNAME                    1405
#define IDC_EDITDESCRIPTION             1406
#define IDC_QUICKSAVE                   1408
#define IDC_QUICKLOAD                   1409
#define IDC_CREATEHF                    1500
#define IDC_HFSIZE                      1501
#define IDC_LINEMODE                    1502
#define IDC_SOCKETS                     1503
#define IDC_RESETAMIGA                  1504
#define IDC_QUITEMU                     1505
#define IDC_TEST16BIT                   1506
#define IDC_MAPDRIVES                   1507
#define IDC_CPUTEXT                     1508
#define IDC_SWAP                        1509
#define IDC_CACHETEXT                   1509
#define IDC_SELECTRESTEXT               1510
#define IDC_SCREENRESTEXT               1511
#define IDC_WIDTHTEXT                   1512
#define IDC_HEIGHTTEXT                  1513
#define IDC_SETTINGSTEXT                1514
#define IDC_REFRESHTEXT                 1515
#define IDC_DISABLE1                    1516
#define IDC_DISABLE2                    1517
#define IDC_DISABLE3                    1518
#define IDC_XCENTER                     1518
#define IDC_YCENTER                     1519
#define IDC_OCS                         1520
#define IDC_ECS_AGNUS                   1521
#define IDC_ECS_DENISE                  1522
#define IDC_ECS                         1523
#define IDC_AGA                         1524
#define IDC_NTSC                        1525
#define IDC_NOSPEED                     1527
#define IDC_NOSOUND                     1528
#define IDC_MIDI                        1529
#define IDC_KICKSHIFTER                 1530
#define IDC_MIDI2                       1530
#define IDC_D0                          1532
#define IDC_D1                          1533
#define IDC_D2                          1534
#define IDC_D3                          1535
#define IDC_D4                          1536
#define IDC_D5                          1537
#define IDC_D6                          1538
#define IDC_D7                          1539
#define IDC_A0                          1540
#define IDC_A1                          1541
#define IDC_A2                          1542
#define IDC_A3                          1543
#define IDC_A4                          1544
#define IDC_A5                          1545
#define IDC_A6                          1546
#define IDC_A7                          1547
#define IDC_USP                         1548
#define IDC_SSP                         1549
#define IDC_PC                          1550
#define IDC_T1                          1551
#define IDC_T2                          1552
#define IDC_T3                          1553
#define IDC_SHARED                      1553
#define IDC_T4                          1554
#define IDC_T5                          1555
#define IDC_T6                          1556
#define IDC_T7                          1557
#define IDC_T8                          1558
#define IDC_T9                          1559
#define IDC_T10                         1560
#define IDC_T11                         1561
#define IDC_T12                         1562
#define IDC_T13                         1563
#define IDC_T14                         1564
#define IDC_T15                         1565
#define IDC_T16                         1566
#define IDC_VIEWINFO                    1568
#define IDC_SETINFO                     1569
#define IDC_FLOPPYSLIDER                1570
#define IDC_FLOPPYSLIDERTEXT            1571
#define IDC_FLOPPYSPEED                 1572
#define IDC_GUILANGUAGE_LIST            1573
#define IDC_SOUNDBUFFERRAM              1574
#define IDC_SOUNDBUFFERTEXT             1576
#define IDC_SOUNDBUFFERMEM              1577
#define IDC_HARDFLUSH                   1578
#define IDC_CONSTJUMP                   1579
#define IDC_JITFPU                      1580
#define IDC_NOFLAGS                     1581
#define IDC_CS_CACHE_TEXT               1582
#define IDC_FORCE                       1583
#define IDC_COLLISIONS                  1584
#define IDC_DISASSEMBLY                 1585
#define IDC_CTRLF11                     1586
#define IDC_FASTCOPPER                  1588
#define IDC_COLLISION0                  1589
#define IDC_COLLISION1                  1590
#define IDC_AUDIOSYNC                   1590
#define IDC_COLLISION2                  1591
#define IDC_COLLISION3                  1592
#define IDC_SOUNDLAGSLIDER              1592
#define IDC_SOUNDLAGCAPTION             1594
#define IDC_SYNCPARAMS                  1595
#define IDC_SOUNDLAGTEXT                1596
#define IDC_SOUNDSPEEDSLIDER            1598
#define IDC_SOUNDSPEEDTEXT              1599
#define IDC_SOUNDSPEEDCAPTION           1600
#define IDC_NOOVERLAY                   1601
#define IDC_ROMFILE2TEXT                1602
#define IDC_ROMTEXT                     1603
#define IDC_KEYTEXT                     1604
#define IDC_CD32                        1605
#define IDC_AKIKOC2P                    1605
#define IDC_CDDEVICE                    1606

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1607
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
